# Cloudflare Pages config for Next.js
name = "litlabs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages@1"

# Pages project settings
[[pages_build_output_dir]]
dir = ".vercel/output/static"
